# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0eprotocol.proto\x12\x0fprogramus.proto\"\x1c\n\x0bTestMessage\x12\r\n\x05value\x18\x01 \x01(\t\"o\n\x0eGenericMessage\x12\x11\n\tsessionId\x18\x01 \x01(\x04\x12\x11\n\trequestId\x18\x02 \x01(\x04\x12,\n\x04test\x18\x64 \x01(\x0b\x32\x1c.programus.proto.TestMessageH\x00\x42\t\n\x07payloadb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocol_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _TESTMESSAGE._serialized_start = 35
    _TESTMESSAGE._serialized_end = 63
    _GENERICMESSAGE._serialized_start = 65
    _GENERICMESSAGE._serialized_end = 176
# @@protoc_insertion_point(module_scope)
