"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.empty_pb2
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class TestMessage(google.protobuf.message.Message):
    """TODO(bgrzesik): delete me"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUE_FIELD_NUMBER: builtins.int
    value: builtins.str
    def __init__(
        self,
        *,
        value: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["value", b"value"]) -> None: ...

global___TestMessage = TestMessage

@typing_extensions.final
class ErrorMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DESCRIPTION_FIELD_NUMBER: builtins.int
    description: builtins.str
    def __init__(
        self,
        *,
        description: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["description", b"description"]) -> None: ...

global___ErrorMessage = ErrorMessage

@typing_extensions.final
class SetSessionId(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSIONID_FIELD_NUMBER: builtins.int
    sessionId: builtins.int
    def __init__(
        self,
        *,
        sessionId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["sessionId", b"sessionId"]) -> None: ...

global___SetSessionId = SetSessionId

@typing_extensions.final
class Board(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    FAVOURITE_FIELD_NUMBER: builtins.int
    name: builtins.str
    favourite: builtins.bool
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        favourite: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["favourite", b"favourite", "name", b"name"]) -> None: ...

global___Board = Board

@typing_extensions.final
class GetBoardsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___GetBoardsRequest = GetBoardsRequest

@typing_extensions.final
class GetBoardsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ALL_FIELD_NUMBER: builtins.int
    FAVORITES_FIELD_NUMBER: builtins.int
    @property
    def all(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Board]: ...
    @property
    def favorites(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Board]: ...
    def __init__(
        self,
        *,
        all: collections.abc.Iterable[global___Board] | None = ...,
        favorites: collections.abc.Iterable[global___Board] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["all", b"all", "favorites", b"favorites"]) -> None: ...

global___GetBoardsResponse = GetBoardsResponse

@typing_extensions.final
class PutBoardsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ALL_FIELD_NUMBER: builtins.int
    FAVORITES_FIELD_NUMBER: builtins.int
    @property
    def all(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Board]: ...
    @property
    def favorites(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Board]: ...
    def __init__(
        self,
        *,
        all: collections.abc.Iterable[global___Board] | None = ...,
        favorites: collections.abc.Iterable[global___Board] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["all", b"all", "favorites", b"favorites"]) -> None: ...

global___PutBoardsRequest = PutBoardsRequest

@typing_extensions.final
class PutBoardsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    success: builtins.bool
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["success", b"success"]) -> None: ...

global___PutBoardsResponse = PutBoardsResponse

@typing_extensions.final
class Firmware(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    FAVOURITE_FIELD_NUMBER: builtins.int
    name: builtins.str
    favourite: builtins.bool
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        favourite: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["favourite", b"favourite", "name", b"name"]) -> None: ...

global___Firmware = Firmware

@typing_extensions.final
class GetFirmwareRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___GetFirmwareRequest = GetFirmwareRequest

@typing_extensions.final
class GetFirmwareResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ALL_FIELD_NUMBER: builtins.int
    FAVORITES_FIELD_NUMBER: builtins.int
    @property
    def all(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Firmware]: ...
    @property
    def favorites(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Firmware]: ...
    def __init__(
        self,
        *,
        all: collections.abc.Iterable[global___Firmware] | None = ...,
        favorites: collections.abc.Iterable[global___Firmware] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["all", b"all", "favorites", b"favorites"]) -> None: ...

global___GetFirmwareResponse = GetFirmwareResponse

@typing_extensions.final
class PutFirmwareRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ALL_FIELD_NUMBER: builtins.int
    FAVORITES_FIELD_NUMBER: builtins.int
    @property
    def all(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Firmware]: ...
    @property
    def favorites(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Firmware]: ...
    def __init__(
        self,
        *,
        all: collections.abc.Iterable[global___Firmware] | None = ...,
        favorites: collections.abc.Iterable[global___Firmware] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["all", b"all", "favorites", b"favorites"]) -> None: ...

global___PutFirmwareRequest = PutFirmwareRequest

@typing_extensions.final
class PutFirmwareResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    success: builtins.bool
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["success", b"success"]) -> None: ...

global___PutFirmwareResponse = PutFirmwareResponse

@typing_extensions.final
class FlashRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FIRMWARE_FIELD_NUMBER: builtins.int
    BOARD_FIELD_NUMBER: builtins.int
    @property
    def firmware(self) -> global___Firmware: ...
    @property
    def board(self) -> global___Board: ...
    def __init__(
        self,
        *,
        firmware: global___Firmware | None = ...,
        board: global___Board | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["board", b"board", "firmware", b"firmware"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["board", b"board", "firmware", b"firmware"]) -> None: ...

global___FlashRequest = FlashRequest

@typing_extensions.final
class FlashResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    success: builtins.bool
    message: builtins.str
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["message", b"message", "success", b"success"]) -> None: ...

global___FlashResponse = FlashResponse

@typing_extensions.final
class DeviceUpdateStatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Status:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _StatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[DeviceUpdateStatus._Status.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNREACHABLE: DeviceUpdateStatus._Status.ValueType  # 0
        READY: DeviceUpdateStatus._Status.ValueType  # 1
        FLASHING: DeviceUpdateStatus._Status.ValueType  # 2
        ERROR: DeviceUpdateStatus._Status.ValueType  # 3

    class Status(_Status, metaclass=_StatusEnumTypeWrapper): ...
    UNREACHABLE: DeviceUpdateStatus.Status.ValueType  # 0
    READY: DeviceUpdateStatus.Status.ValueType  # 1
    FLASHING: DeviceUpdateStatus.Status.ValueType  # 2
    ERROR: DeviceUpdateStatus.Status.ValueType  # 3

    STATUS_FIELD_NUMBER: builtins.int
    FLASHINGPROGRESS_FIELD_NUMBER: builtins.int
    IMAGE_FIELD_NUMBER: builtins.int
    status: global___DeviceUpdateStatus.Status.ValueType
    flashingProgress: builtins.float
    image: builtins.str
    def __init__(
        self,
        *,
        status: global___DeviceUpdateStatus.Status.ValueType = ...,
        flashingProgress: builtins.float = ...,
        image: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["flashingProgress", b"flashingProgress", "image", b"image", "status", b"status"]) -> None: ...

global___DeviceUpdateStatus = DeviceUpdateStatus

@typing_extensions.final
class FileUpload(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _FileType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _FileTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[FileUpload._FileType.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        FIRMWARE: FileUpload._FileType.ValueType  # 0

    class FileType(_FileType, metaclass=_FileTypeEnumTypeWrapper): ...
    FIRMWARE: FileUpload.FileType.ValueType  # 0

    class _Result:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ResultEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[FileUpload._Result.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        OK: FileUpload._Result.ValueType  # 0
        INVALID_CHECKSUM: FileUpload._Result.ValueType  # 1
        IO_ERROR: FileUpload._Result.ValueType  # 2
        ALREADY_EXISTS: FileUpload._Result.ValueType  # 3

    class Result(_Result, metaclass=_ResultEnumTypeWrapper): ...
    OK: FileUpload.Result.ValueType  # 0
    INVALID_CHECKSUM: FileUpload.Result.ValueType  # 1
    IO_ERROR: FileUpload.Result.ValueType  # 2
    ALREADY_EXISTS: FileUpload.Result.ValueType  # 3

    @typing_extensions.final
    class Start(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        NAME_FIELD_NUMBER: builtins.int
        SIZE_FIELD_NUMBER: builtins.int
        CHUNKS_FIELD_NUMBER: builtins.int
        TYPE_FIELD_NUMBER: builtins.int
        name: builtins.str
        size: builtins.int
        chunks: builtins.int
        type: global___FileUpload.FileType.ValueType
        def __init__(
            self,
            *,
            name: builtins.str = ...,
            size: builtins.int = ...,
            chunks: builtins.int = ...,
            type: global___FileUpload.FileType.ValueType = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["chunks", b"chunks", "name", b"name", "size", b"size", "type", b"type"]) -> None: ...

    @typing_extensions.final
    class Part(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        PARTNO_FIELD_NUMBER: builtins.int
        CHUNK_FIELD_NUMBER: builtins.int
        partNo: builtins.int
        chunk: builtins.bytes
        def __init__(
            self,
            *,
            partNo: builtins.int = ...,
            chunk: builtins.bytes = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["chunk", b"chunk", "partNo", b"partNo"]) -> None: ...

    @typing_extensions.final
    class Finish(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        CHECKSUM_FIELD_NUMBER: builtins.int
        checksum: builtins.bytes
        def __init__(
            self,
            *,
            checksum: builtins.bytes = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["checksum", b"checksum"]) -> None: ...

    UID_FIELD_NUMBER: builtins.int
    START_FIELD_NUMBER: builtins.int
    PART_FIELD_NUMBER: builtins.int
    FINISH_FIELD_NUMBER: builtins.int
    RESULT_FIELD_NUMBER: builtins.int
    uid: builtins.int
    @property
    def start(self) -> global___FileUpload.Start: ...
    @property
    def part(self) -> global___FileUpload.Part: ...
    @property
    def finish(self) -> global___FileUpload.Finish: ...
    result: global___FileUpload.Result.ValueType
    def __init__(
        self,
        *,
        uid: builtins.int = ...,
        start: global___FileUpload.Start | None = ...,
        part: global___FileUpload.Part | None = ...,
        finish: global___FileUpload.Finish | None = ...,
        result: global___FileUpload.Result.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["event", b"event", "finish", b"finish", "part", b"part", "result", b"result", "start", b"start"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["event", b"event", "finish", b"finish", "part", b"part", "result", b"result", "start", b"start", "uid", b"uid"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["event", b"event"]) -> typing_extensions.Literal["start", "part", "finish", "result"] | None: ...

global___FileUpload = FileUpload

@typing_extensions.final
class DebuggerStart(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TARGET_FIELD_NUMBER: builtins.int
    FIRMWARE_FIELD_NUMBER: builtins.int
    target: builtins.str
    firmware: builtins.str
    def __init__(
        self,
        *,
        target: builtins.str = ...,
        firmware: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["firmware", b"firmware", "target", b"target"]) -> None: ...

global___DebuggerStart = DebuggerStart

@typing_extensions.final
class DebuggerStarted(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSIONID_FIELD_NUMBER: builtins.int
    sessionId: builtins.int
    def __init__(
        self,
        *,
        sessionId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["sessionId", b"sessionId"]) -> None: ...

global___DebuggerStarted = DebuggerStarted

@typing_extensions.final
class DebuggerStop(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___DebuggerStop = DebuggerStop

@typing_extensions.final
class DebuggerLine(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ORDINAL_FIELD_NUMBER: builtins.int
    LINE_FIELD_NUMBER: builtins.int
    ordinal: builtins.int
    line: builtins.str
    def __init__(
        self,
        *,
        ordinal: builtins.int = ...,
        line: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["line", b"line", "ordinal", b"ordinal"]) -> None: ...

global___DebuggerLine = DebuggerLine

@typing_extensions.final
class DeleteFile(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name", b"name"]) -> None: ...

global___DeleteFile = DeleteFile

@typing_extensions.final
class GenericMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSIONID_FIELD_NUMBER: builtins.int
    REQUEST_FIELD_NUMBER: builtins.int
    RESPONSE_FIELD_NUMBER: builtins.int
    SETSESSIONID_FIELD_NUMBER: builtins.int
    HEARTBEAT_FIELD_NUMBER: builtins.int
    OK_FIELD_NUMBER: builtins.int
    GETBOARDSREQUEST_FIELD_NUMBER: builtins.int
    GETBOARDSRESPONSE_FIELD_NUMBER: builtins.int
    PUTBOARDSREQUEST_FIELD_NUMBER: builtins.int
    PUTBOARDSRESPONSE_FIELD_NUMBER: builtins.int
    GETFIRMWAREREQUEST_FIELD_NUMBER: builtins.int
    GETFIRMWARERESPONSE_FIELD_NUMBER: builtins.int
    PUTFIRMWAREREQUEST_FIELD_NUMBER: builtins.int
    PUTFIRMWARERESPONSE_FIELD_NUMBER: builtins.int
    FLASHREQUEST_FIELD_NUMBER: builtins.int
    FLASHRESPONSE_FIELD_NUMBER: builtins.int
    DEVICEUPDATESTATUS_FIELD_NUMBER: builtins.int
    FILEUPLOAD_FIELD_NUMBER: builtins.int
    DEBUGGERSTART_FIELD_NUMBER: builtins.int
    DEBUGGERSTARTED_FIELD_NUMBER: builtins.int
    DEBUGGERSTOP_FIELD_NUMBER: builtins.int
    DEBUGGERLINE_FIELD_NUMBER: builtins.int
    DELETEFILE_FIELD_NUMBER: builtins.int
    TEST_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    sessionId: builtins.int
    request: builtins.int
    response: builtins.int
    @property
    def setSessionId(self) -> global___SetSessionId: ...
    @property
    def heartbeat(self) -> google.protobuf.empty_pb2.Empty: ...
    @property
    def ok(self) -> google.protobuf.empty_pb2.Empty: ...
    @property
    def getBoardsRequest(self) -> global___GetBoardsRequest: ...
    @property
    def getBoardsResponse(self) -> global___GetBoardsResponse: ...
    @property
    def putBoardsRequest(self) -> global___PutBoardsRequest: ...
    @property
    def putBoardsResponse(self) -> global___PutBoardsResponse: ...
    @property
    def getFirmwareRequest(self) -> global___GetFirmwareRequest: ...
    @property
    def getFirmwareResponse(self) -> global___GetFirmwareResponse: ...
    @property
    def putFirmwareRequest(self) -> global___PutFirmwareRequest: ...
    @property
    def putFirmwareResponse(self) -> global___PutFirmwareResponse: ...
    @property
    def flashRequest(self) -> global___FlashRequest: ...
    @property
    def flashResponse(self) -> global___FlashResponse: ...
    @property
    def deviceUpdateStatus(self) -> global___DeviceUpdateStatus:
        """Response: Ok(102)"""
    @property
    def fileUpload(self) -> global___FileUpload: ...
    @property
    def debuggerStart(self) -> global___DebuggerStart: ...
    @property
    def debuggerStarted(self) -> global___DebuggerStarted: ...
    @property
    def debuggerStop(self) -> global___DebuggerStop:
        """Response: Ok(102)"""
    @property
    def debuggerLine(self) -> global___DebuggerLine:
        """Response: Ok(102)"""
    @property
    def deleteFile(self) -> global___DeleteFile: ...
    @property
    def test(self) -> global___TestMessage: ...
    @property
    def error(self) -> global___ErrorMessage: ...
    def __init__(
        self,
        *,
        sessionId: builtins.int = ...,
        request: builtins.int = ...,
        response: builtins.int = ...,
        setSessionId: global___SetSessionId | None = ...,
        heartbeat: google.protobuf.empty_pb2.Empty | None = ...,
        ok: google.protobuf.empty_pb2.Empty | None = ...,
        getBoardsRequest: global___GetBoardsRequest | None = ...,
        getBoardsResponse: global___GetBoardsResponse | None = ...,
        putBoardsRequest: global___PutBoardsRequest | None = ...,
        putBoardsResponse: global___PutBoardsResponse | None = ...,
        getFirmwareRequest: global___GetFirmwareRequest | None = ...,
        getFirmwareResponse: global___GetFirmwareResponse | None = ...,
        putFirmwareRequest: global___PutFirmwareRequest | None = ...,
        putFirmwareResponse: global___PutFirmwareResponse | None = ...,
        flashRequest: global___FlashRequest | None = ...,
        flashResponse: global___FlashResponse | None = ...,
        deviceUpdateStatus: global___DeviceUpdateStatus | None = ...,
        fileUpload: global___FileUpload | None = ...,
        debuggerStart: global___DebuggerStart | None = ...,
        debuggerStarted: global___DebuggerStarted | None = ...,
        debuggerStop: global___DebuggerStop | None = ...,
        debuggerLine: global___DebuggerLine | None = ...,
        deleteFile: global___DeleteFile | None = ...,
        test: global___TestMessage | None = ...,
        error: global___ErrorMessage | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["debuggerLine", b"debuggerLine", "debuggerStart", b"debuggerStart", "debuggerStarted", b"debuggerStarted", "debuggerStop", b"debuggerStop", "deleteFile", b"deleteFile", "deviceUpdateStatus", b"deviceUpdateStatus", "error", b"error", "fileUpload", b"fileUpload", "flashRequest", b"flashRequest", "flashResponse", b"flashResponse", "getBoardsRequest", b"getBoardsRequest", "getBoardsResponse", b"getBoardsResponse", "getFirmwareRequest", b"getFirmwareRequest", "getFirmwareResponse", b"getFirmwareResponse", "heartbeat", b"heartbeat", "id", b"id", "ok", b"ok", "payload", b"payload", "putBoardsRequest", b"putBoardsRequest", "putBoardsResponse", b"putBoardsResponse", "putFirmwareRequest", b"putFirmwareRequest", "putFirmwareResponse", b"putFirmwareResponse", "request", b"request", "response", b"response", "setSessionId", b"setSessionId", "test", b"test"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["debuggerLine", b"debuggerLine", "debuggerStart", b"debuggerStart", "debuggerStarted", b"debuggerStarted", "debuggerStop", b"debuggerStop", "deleteFile", b"deleteFile", "deviceUpdateStatus", b"deviceUpdateStatus", "error", b"error", "fileUpload", b"fileUpload", "flashRequest", b"flashRequest", "flashResponse", b"flashResponse", "getBoardsRequest", b"getBoardsRequest", "getBoardsResponse", b"getBoardsResponse", "getFirmwareRequest", b"getFirmwareRequest", "getFirmwareResponse", b"getFirmwareResponse", "heartbeat", b"heartbeat", "id", b"id", "ok", b"ok", "payload", b"payload", "putBoardsRequest", b"putBoardsRequest", "putBoardsResponse", b"putBoardsResponse", "putFirmwareRequest", b"putFirmwareRequest", "putFirmwareResponse", b"putFirmwareResponse", "request", b"request", "response", b"response", "sessionId", b"sessionId", "setSessionId", b"setSessionId", "test", b"test"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["id", b"id"]) -> typing_extensions.Literal["request", "response"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["payload", b"payload"]) -> typing_extensions.Literal["setSessionId", "heartbeat", "ok", "getBoardsRequest", "getBoardsResponse", "putBoardsRequest", "putBoardsResponse", "getFirmwareRequest", "getFirmwareResponse", "putFirmwareRequest", "putFirmwareResponse", "flashRequest", "flashResponse", "deviceUpdateStatus", "fileUpload", "debuggerStart", "debuggerStarted", "debuggerStop", "debuggerLine", "deleteFile", "test", "error"] | None: ...

global___GenericMessage = GenericMessage
